import { LoaderFunction, redirect, ActionFunction, json } from "@remix-run/node";
import { MetaTagsDto } from "~/application/dtos/seo/MetaTagsDto";
import NotificationService from "~/modules/notifications/services/NotificationService";
import { EntitiesApi } from "~/utils/api/EntitiesApi";
import { RowCommentsApi } from "~/utils/api/RowCommentsApi";
import { RowsApi } from "~/utils/api/RowsApi";
import { WorkflowsApi } from "~/utils/api/WorkflowsApi";
import UrlUtils from "~/utils/app/UrlUtils";
import { setRowCommentReaction } from "~/utils/db/entities/rowCommentReaction.db.server";
import { getRowComment, updateRowComment } from "~/utils/db/entities/rowComments.db.server";
import { createRowTask, getRowTask, updateRowTask, deleteRowTask } from "~/utils/db/entities/rowTasks.db.server";
import { getUser } from "~/utils/db/users.db.server";
import EntityHelper from "~/utils/helpers/EntityHelper";
import { verifyUserHasPermission, getEntityPermission } from "~/utils/helpers/PermissionsHelper";
import RowHelper from "~/utils/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";
import { createMetrics } from "~/modules/metrics/utils/MetricTracker";
import FormulaService from "~/modules/formulas/services/FormulaService";
import PromptBuilderService from "~/modules/promptBuilder/services/PromptBuilderService";

export namespace Rows_Overview {
  export type LoaderData = {
    meta: MetaTagsDto;
    rowData: RowsApi.GetRowData;
    routes: EntitiesApi.Routes;
    relationshipRows: RowsApi.GetRelationshipRowsData;
  };
  export let loader: LoaderFunction = async ({ request, params }) => {
    const { time, getServerTimingHeader } = await createMetrics({ request, params }, `[Rows_Overview] ${params.entity}`);
    const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params });
    await time(verifyUserHasPermission(request, getEntityPermission(entity, "read"), tenantId), "verifyUserHasPermission");
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await time(
      RowsApi.get(params.id!, {
        entity,
        tenantId,
        userId,
      }),
      "RowsApi.get"
    );
    await time(
      FormulaService.trigger({ trigger: "BEFORE_VIEWED", rows: [rowData.item], entity: rowData.entity, session: { tenantId, userId }, t }),
      "FormulaService.trigger.BEFORE_VIEWED"
    );
    const data: LoaderData = {
      meta: [{ title: `${t(RowHelper.getTextDescription({ entity, item: rowData.item, t }))} | ${process.env.APP_NAME}` }],
      rowData,
      routes: EntityHelper.getNoCodeRoutes({ request, params }),
      relationshipRows: await time(RowsApi.getRelationshipRows({ entity, tenantId, userId }), "RowsApi.getRelationshipRows"),
    };
    return json(data, { headers: getServerTimingHeader() });
  };

  export type ActionData = {
    updatedRow?: RowsApi.GetRowData;
    success?: string;
    error?: string;
  };
  export const action: ActionFunction = async ({ request, params }) => {
    const { time, getServerTimingHeader } = await createMetrics({ request, params }, `[Rows_Overview] ${params.entity}`);
    const { t, userId, tenantId, entity, form } = await RowsRequestUtils.getAction({ request, params });
    const action = form.get("action")?.toString() ?? "";
    const user = await time(getUser(userId), "getUser");
    const rowData = await time(
      RowsApi.get(params.id!, {
        entity,
        tenantId,
        userId,
      }),
      "RowsApi.get"
    );
    const { item } = rowData;

    if (action === "edit") {
      try {
        const rowValues = RowHelper.getRowPropertiesFromForm({ t, entity, form, existing: item });
        await time(
          RowsApi.update(params.id!, {
            entity,
            tenantId,
            userId,
            rowValues,
          }),
          "RowsApi.update"
        );
      } catch (error: any) {
        return json({ error: error.message }, { status: 400, headers: getServerTimingHeader() });
      }
      // const redirectTo = form.get("redirect")?.toString() || new URL(request.url).searchParams.get("redirect")?.toString();
      // if (redirectTo) {
      //   return redirect(redirectTo, { headers: getServerTimingHeader() });
      // }
      const updatedRow = await time(RowsApi.get(params.id!, { entity }), "RowsApi.get");
      return json({ updatedRow, success: t("shared.saved") }, { headers: getServerTimingHeader() });
    } else if (action === "delete") {
      try {
        await time(
          RowsApi.del(params.id!, {
            entity,
            tenantId,
            userId,
          }),
          "RowsApi.del"
        );
        if (item.createdByUser) {
          await time(
            NotificationService.send({
              channel: "my-rows",
              to: item.createdByUser,
              notification: {
                from: { user },
                message: `${user?.email} deleted ${RowHelper.getTextDescription({ entity, item })}`,
                action: {
                  title: t("shared.view"),
                  url: EntityHelper.getRoutes({ routes: EntityHelper.getNoCodeRoutes({ request, params }), entity, item })?.overview ?? "",
                },
              },
            }),
            "NotificationService.send"
          );
        }
      } catch (error: any) {
        return json({ error: error.message }, { status: 400, headers: getServerTimingHeader() });
      }
      const redirectTo = form.get("redirect")?.toString() || new URL(request.url).searchParams.get("redirect")?.toString();
      if (redirectTo) {
        return redirect(redirectTo, { headers: getServerTimingHeader() });
      }
      const routes = EntityHelper.getNoCodeRoutes({ request, params });
      const listRoute = EntityHelper.getRoutes({ routes, entity })?.list;
      if (listRoute) {
        return redirect(listRoute, { headers: getServerTimingHeader() });
      }
      return json({ deleted: true }, { headers: getServerTimingHeader() });
    } else if (action === "comment") {
      let comment = form.get("comment")?.toString();
      if (!comment) {
        return json({ error: t("shared.invalidForm") }, { status: 400, headers: getServerTimingHeader() });
      }
      await time(
        RowCommentsApi.create(item.id, {
          comment,
          userId,
        }),
        "RowCommentsApi.create"
      );
      if (item.createdByUser) {
        await time(
          NotificationService.send({
            channel: "my-rows",
            to: item.createdByUser,
            notification: {
              from: { user },
              message: `${user?.email} commented on ${RowHelper.getTextDescription({ entity, item })}`,
              action: {
                title: t("shared.view"),
                url: EntityHelper.getRoutes({ routes: EntityHelper.getNoCodeRoutes({ request, params }), entity, item })?.overview ?? "",
              },
            },
          }),
          "NotificationService.send"
        );
      }
      return json({ newComment: comment }, { headers: getServerTimingHeader() });
    } else if (action === "comment-reaction") {
      const rowCommentId = form.get("comment-id")?.toString();
      const reaction = form.get("reaction")?.toString();
      if (!rowCommentId || !reaction) {
        return json({ error: t("shared.invalidForm") }, { status: 400, headers: getServerTimingHeader() });
      }
      await time(getRowComment(rowCommentId), "getRowComment");
      await time(
        setRowCommentReaction({
          createdByUserId: userId,
          rowCommentId,
          reaction,
        }),
        "setRowCommentReaction"
      );
      return json({ newCommentReaction: reaction }, { headers: getServerTimingHeader() });
    } else if (action === "comment-delete") {
      const rowCommentId = form.get("comment-id")?.toString();
      if (!rowCommentId) {
        return json({ error: t("shared.invalidForm") }, { status: 400, headers: getServerTimingHeader() });
      }
      await time(updateRowComment(rowCommentId, { isDeleted: true }), "updateRowComment");
      return json({ deletedComment: rowCommentId }, { headers: getServerTimingHeader() });
    } else if (action === "task-new") {
      const taskTitle = form.get("task-title")?.toString();
      if (!taskTitle) {
        return json({ error: t("shared.invalidForm") }, { status: 400, headers: getServerTimingHeader() });
      }
      const task = await time(
        createRowTask({
          createdByUserId: userId,
          rowId: item.id,
          title: taskTitle,
        }),
        "createRowTask"
      );
      return json({ newTask: task }, { headers: getServerTimingHeader() });
    } else if (action === "task-complete-toggle") {
      const taskId = form.get("task-id")?.toString() ?? "";
      const task = await time(getRowTask(taskId), "getRowTask");
      if (task) {
        if (task.completed) {
          await time(
            updateRowTask(taskId, {
              completed: false,
              completedAt: null,
              completedByUserId: null,
            }),
            "updateRowTask"
          );
        } else {
          await time(
            updateRowTask(taskId, {
              completed: true,
              completedAt: new Date(),
              completedByUserId: userId,
            }),
            "updateRowTask"
          );
        }
      }
      return json({ completedTask: taskId }, { headers: getServerTimingHeader() });
    } else if (action === "task-delete") {
      const taskId = form.get("task-id")?.toString() ?? "";
      const task = await time(getRowTask(taskId), "getRowTask");
      if (task) {
        await time(deleteRowTask(taskId), "deleteRowTask");
      }
      return json({ deletedTask: taskId }, { headers: getServerTimingHeader() });
    } else if (action === "workflow-transition") {
      const actionName = form.get("workflow-action")?.toString() ?? "";
      try {
        const workflowTransition = await time(
          WorkflowsApi.performTransition({
            row: item,
            entity,
            actionName,
            byUserId: userId,
            request,
          }),
          "Rows_Overview.action WorkflowsApi.performTransition"
        );
        if (item.createdByUser) {
          await time(
            NotificationService.send({
              channel: "my-rows",
              to: item.createdByUser,
              notification: {
                from: { user },
                message: `${user?.email} moved ${RowHelper.getTextDescription({ entity, item })} from ${t(
                  workflowTransition.workflowStep.fromState.title
                )} to ${t(workflowTransition.workflowStep.toState.title)}`,
              },
            }),
            "NotificationService.send"
          );
        }
        return json({}, { headers: getServerTimingHeader() });
      } catch (error: any) {
        return json({ error: error.message }, { status: 400, headers: getServerTimingHeader() });
      }
    } else if (action === "workflow-set-manual-state") {
      const stateName = form.get("workflow-state")?.toString() ?? "";
      try {
        if (item.workflowState?.name === stateName) {
          return json({ error: t("workflows.errors.alreadyInState") }, { status: 400, headers: getServerTimingHeader() });
        }
        await time(
          WorkflowsApi.setState({
            entity,
            stateName,
            rowId: item.id,
          }),
          "WorkflowsApi.setState"
        );
        return json({}, { headers: getServerTimingHeader() });
      } catch (error: any) {
        return json({ error: error.message }, { status: 400, headers: getServerTimingHeader() });
      }
    } else if (action === "run-prompt-flow") {
      try {
        const promptFlowExecutionResult = await PromptBuilderService.runFromForm({ request, params, form, tenantId, userId, time });
        // const actionData: ActionData = {
        //   promptFlowExecutionResult,
        // };
        return json({ promptFlowExecutionResult }, { headers: getServerTimingHeader() });
      } catch (e: any) {
        return json({ error: e.message }, { status: 400, headers: getServerTimingHeader() });
      }
    } else {
      return json({ error: t("shared.invalidForm") }, { status: 400, headers: getServerTimingHeader() });
    }
  };
}
